server.port=8761

spring.application.name=discovery-server

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.instance.hostname=discovery-server
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=discovery-server:8761

eureka.instance.status-page-url=http://discovery-server:8761/actuator/info
eureka.instance.health-check-url=http://discovery-server:8761/actuator/health
eureka.instance.home-page-url=http://discovery-server:8761/

# ===============================
# ACTUATOR / HEALTH CHECKS
# ===============================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.diskspace.enabled=true
management.health.liveness.enabled=true
management.health.readiness.enabled=true