server.port=8088

spring.application.name=analytics-service

# ===============================
# SPRING CLOUD CONFIG
# ===============================
spring.config.import=optional:configserver:
spring.cloud.config.enabled=false
spring.cloud.compatibility-verifier.enabled=false
spring.cloud.config.import-check.enabled=false

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hireconnectdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# remove explicit dialect warning drama
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# EUREKA
# ===============================
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/

eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ===============================
# FEIGN
# ===============================
spring.cloud.openfeign.lazy-attributes-resolution=true

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET:hireconnect-super-secret-key-for-jwt-123456789-hireconnect-auth-service}

# ===============================
# SWAGGER / OPENAPI
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.override-with-generic-response=false

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.hireconnect.analytics=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG